clc;clear; close all;

exp = {'Continuous: Untreated',...
'Continuous: Chemo',...
'Continuous: Disulfiram (low)',...
'Continuous: Disulfiram (medium)',...
'Continuous: Disulfiram (high)',...
'Continuous: Disulfiram (low) + Chemo',...
'Continuous: Disulfiram (medium) + Chemo',...
'Continuous: Disulfiram (high) + Chemo',...
'Sequential: Chemo > Disulfiram (low)',...
'Sequential: Chemo > Disulfiram (medium)',...
'Sequential: Chemo > Disulfiram (high)',...
'Sequential: Disulfiram (low) > Chemo',...
'Sequential: Disulfiram (medium) > Chemo',...
'Sequential: Disulfiram (high) > Chemo',...
'Layered: Continuous Chemo + Disulfiram (low)',...
'Layered: Continuous Chemo + Disulfiram (medium)',...
'Layered: Continuous Chemo + Disulfiram (high)',...
'Layered: Continuous Disulfiram (low) + Chemo',...
'Layered: Continuous Disulfiram (medium) + Chemo',...
'Layered: Continuous Disulfiram (high) + Chemo',...
'Staggered: Chemo > Disulfiram > Chemo > Disulfiram (low)',...
'Staggered: Chemo > Disulfiram > Chemo > Disulfiram (medium)',...
'Staggered: Chemo > Disulfiram > Chemo > Disulfiram (high)',...
'Staggered: Disulfiram > Chemo > Disulfiram > Chemo (low)',...
'Staggered: Disulfiram > Chemo > Disulfiram > Chemo (medium)',...
'Staggered: Disulfiram > Chemo > Disulfiram > Chemo (high)'};


%% cell line / drug:
cell_line = 'MCF7'; % MCF7, T47D
drug = 'Doxo'; % Doxo, Pacli

T = [0,4,7,11,14,18,21,25,28]';
j=1;
for ex = exp(1:8)
    char(ex)
    [fraction,YFP,RFP] = getRawData(char(ex),cell_line,drug);

    % step 1: convert to cell counts:
    [YFPcell_count,RFPcell_count] = convertCellCount(YFP,RFP,cell_line,drug);

    M = T;
    Nr = 3;
    for i = 1:1:length(fraction)
        i0 = (i-1)*Nr + 1;
        iF = i0 + Nr - 1;
        Scount = YFPcell_count(:,i0:iF);
        Rcount = RFPcell_count(:,i0:iF);
        M=[M,Scount,Rcount];
    end
    
    filename = strcat('_CSV/',cell_line,'-',drug,'R/condition',num2str(j),'.csv');

    header=getHeader(char(ex),Nr,fraction);
    writeCSVHeader(filename,char(header));
    dlmwrite(filename,M,'-append','precision','%10.0f');
    j=j+1;
end


% add to the CSV file:
% Time | Ratio1_S_replicate1 | Ratio1_S_replicate2 ... | Ratio1_R_replicate1 | Ratio1_R_replicate2 ... 
function header=getHeader(experiment_name,Nr,fraction)
header = experiment_name;
    for i = 1:length(fraction)
        for k = {'S','R'}
            for j = 1:Nr
                header = strcat(header,',',char(k),'(',num2str(fraction(i)),'%%) Rep',num2str(j));
            end
        end
    end
end
