% S, R are in units of cell count (#)
function [t,chemo,disu] = getDosing(experiment,cell_line,drug)
exp = {'Continuous: Untreated',...
'Continuous: Chemo',...
'Continuous: Disulfiram (low)',...
'Continuous: Disulfiram (medium)',...
'Continuous: Disulfiram (high)',...
'Continuous: Disulfiram (low) + Chemo',...
'Continuous: Disulfiram (medium) + Chemo',...
'Continuous: Disulfiram (high) + Chemo',...
'Sequential: Chemo > Disulfiram (low)',...
'Sequential: Chemo > Disulfiram (medium)',...
'Sequential: Chemo > Disulfiram (high)',...
'Sequential: Disulfiram (low) > Chemo',...
'Sequential: Disulfiram (medium) > Chemo',...
'Sequential: Disulfiram (high) > Chemo',...
'Layered: Continuous Chemo + Disulfiram (low)',...
'Layered: Continuous Chemo + Disulfiram (medium)',...
'Layered: Continuous Chemo + Disulfiram (high)',...
'Layered: Continuous Disulfiram (low) + Chemo',...
'Layered: Continuous Disulfiram (medium) + Chemo',...
'Layered: Continuous Disulfiram (high) + Chemo',...
'Staggered: Chemo > Disulfiram > Chemo > Disulfiram (low)',...
'Staggered: Chemo > Disulfiram > Chemo > Disulfiram (medium)',...
'Staggered: Chemo > Disulfiram > Chemo > Disulfiram (high)',...
'Staggered: Disulfiram > Chemo > Disulfiram > Chemo (low)',...
'Staggered: Disulfiram > Chemo > Disulfiram > Chemo (medium)',...
'Staggered: Disulfiram > Chemo > Disulfiram > Chemo (high)'};

filename = strcat('_Excel/',cell_line,'_',drug,'R_master_fluorescence_results.xlsx');

j=100;
for i = 1:length(exp)
    if strcmp(experiment,char(exp(i)) )
        j=i-1;
    end
end



% dosing tab should be second:
[chemo,~,~] = xlsread(filename,2,'C4:F29');
[disu,~,~] = xlsread(filename,2,'H4:K29');

t=[7,14,21,28]-3.5;
chemo = chemo(j+1,:);%./25;
disu = disu(j+1,:);%./500;

end









