% S, R are in units of cell count (#)
function [fR,Scount,Rcount] = getRawData(experiment,cell_line,drug)
exp = {'Continuous: Untreated',...
'Continuous: Chemo',...
'Continuous: Disulfiram (low)',...
'Continuous: Disulfiram (medium)',...
'Continuous: Disulfiram (high)',...
'Continuous: Disulfiram (low) + Chemo',...
'Continuous: Disulfiram (medium) + Chemo',...
'Continuous: Disulfiram (high) + Chemo',...
'Sequential: Chemo > Disulfiram (low)',...
'Sequential: Chemo > Disulfiram (medium)',...
'Sequential: Chemo > Disulfiram (high)',...
'Sequential: Disulfiram (low) > Chemo',...
'Sequential: Disulfiram (medium) > Chemo',...
'Sequential: Disulfiram (high) > Chemo',...
'Layered: Continuous Chemo + Disulfiram (low)',...
'Layered: Continuous Chemo + Disulfiram (medium)',...
'Layered: Continuous Chemo + Disulfiram (high)',...
'Layered: Continuous Disulfiram (low) + Chemo',...
'Layered: Continuous Disulfiram (medium) + Chemo',...
'Layered: Continuous Disulfiram (high) + Chemo',...
'Staggered: Chemo > Disulfiram > Chemo > Disulfiram (low)',...
'Staggered: Chemo > Disulfiram > Chemo > Disulfiram (medium)',...
'Staggered: Chemo > Disulfiram > Chemo > Disulfiram (high)',...
'Staggered: Disulfiram > Chemo > Disulfiram > Chemo (low)',...
'Staggered: Disulfiram > Chemo > Disulfiram > Chemo (medium)',...
'Staggered: Disulfiram > Chemo > Disulfiram > Chemo (high)'};

filename = strcat('_Excel/',char(cell_line),'_',char(drug),'R_master_fluorescence_results.xlsx');

j=100;
for i = 1:length(exp)
    if strcmp(experiment,char(exp(i)) )
        j=i-1;
    end
end

delta_i = j*15; % shift over appropriate amount:


fR = [0, 0.25, 0.50, 0.75, 1.00];

%% Raw flur sens: % B20 - B28
%% Raw flur res: % B35 - B43
[Sall,~,~] = xlsread(filename,1,'B20:OA28');
[Rall,~,~] = xlsread(filename,1,'B35:OA43');

% rows are timepoints, columns are S/R ratios
S = Sall(:,delta_i+1:(delta_i+15));
R = Rall(:,delta_i+1:(delta_i+15));



Scount=S;
Rcount=R;
% [Scount,Rcount]=convertCellCount(S,R,cell_line,drug);


end









